"""
Python Service Handler

Creates Python applications with FastAPI/Flask, Gunicorn, and Kubernetes deployment.
"""

import os
from typing import Dict, Any
from .base import BaseHandler, ServiceConfig


class PythonServiceHandler(BaseHandler):
    """Handler for python-service template"""
    
    template_id = "python-service"
    
    def get_template_subdir(self) -> str:
        return "python"
    
    def validate(self) -> tuple[bool, list[str]]:
        """Validate Python service configuration"""
        errors = []
        
        # Required fields
        if not self.service.name:
            errors.append("service_name is required")
        
        # Validate name format
        name = self.service.name
        if not name.replace('-', '').replace('_', '').isalnum():
            errors.append("service_name must contain only alphanumeric characters, hyphens, and underscores")
        
        # Validate port
        port = self.service.get("port", 8000)
        if not isinstance(port, int) or port < 1 or port > 65535:
            errors.append("port must be between 1 and 65535")
        
        return len(errors) == 0, errors
    
    def get_context(self) -> Dict[str, Any]:
        """Build template context from form config"""
        config = self.service.config
        
        return {
            "name": self.service.name,
            "namespace": self.service.namespace,
            "image": self.get_image_name(),
            "environment": config.get("environment", "dev"),
            "python_version": config.get("python_version", "3.11"),
            "port": config.get("port", 8000),
            "gunicorn_workers": config.get("gunicorn_workers", 4),
            "cpu_limit": config.get("cpu_limit", "500m"),
            "memory_limit": config.get("memory_limit", "512Mi"),
            "cpu_request": config.get("request_cpu", "250m"),
            "memory_request": config.get("request_memory", "256Mi"),
            "replicas": config.get("replicas", 2),
            "enable_metrics": config.get("enable_metrics", True),
            "enable_health_check": config.get("enable_health_check", True),
            "enable_ingress": config.get("enable_ingress", False),
            "log_level": config.get("log_level", "INFO"),
            "extra_env_vars": config.get("extra_env_vars", {}),
        }
    
    def generate_code(self) -> str:
        """Generate Python application code"""
        output_dir = os.path.join(self.base_dir, "apps", self.service.name)
        os.makedirs(output_dir, exist_ok=True)
        
        context = self.get_context()
        
        # Generate main.py
        main_py = self._generate_main_py(context)
        self.write_file(output_dir, "main.py", main_py)
        
        # Generate requirements.txt
        requirements = self._generate_requirements(context)
        self.write_file(output_dir, "requirements.txt", requirements)
        
        # Generate Dockerfile
        dockerfile = self._generate_dockerfile(context)
        self.write_file(output_dir, "Dockerfile", dockerfile)
        
        return output_dir
    
    def _generate_main_py(self, context: Dict[str, Any]) -> str:
        """Generate FastAPI application"""
        enable_metrics = context.get("enable_metrics", True)
        
        code = f'''"""
{context["name"]} - Python Service
Generated by HubbOps IDP
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import logging
import os

# Configure logging
logging.basicConfig(
    level=logging.{context.get("log_level", "INFO")},
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="{context["name"]}",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

'''
        if enable_metrics:
            code += '''
# Prometheus metrics
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from fastapi.responses import Response
import time

REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status"]
)

REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency",
    ["method", "endpoint"]
)

@app.middleware("http")
async def metrics_middleware(request, call_next):
    start_time = time.time()
    response = await call_next(request)
    duration = time.time() - start_time
    
    REQUEST_COUNT.labels(
        method=request.method,
        endpoint=request.url.path,
        status=response.status_code
    ).inc()
    
    REQUEST_LATENCY.labels(
        method=request.method,
        endpoint=request.url.path
    ).observe(duration)
    
    return response

@app.get("/metrics")
async def metrics():
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)

'''

        code += '''
@app.get("/")
async def root():
    return {"service": "''' + context["name"] + '''", "status": "running"}

@app.get("/health")
async def health():
    return {"status": "healthy"}

@app.get("/ready")
async def ready():
    return {"status": "ready"}

# Add your application routes below
# Example:
# @app.get("/api/items")
# async def list_items():
#     return {"items": []}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=''' + str(context.get("port", 8000)) + ''')
'''
        return code
    
    def _generate_requirements(self, context: Dict[str, Any]) -> str:
        """Generate requirements.txt"""
        requirements = [
            "fastapi==0.109.0",
            "uvicorn[standard]==0.27.0",
            "gunicorn==21.2.0",
            "pydantic==2.5.3",
        ]
        
        if context.get("enable_metrics", True):
            requirements.append("prometheus-client==0.19.0")
        
        return "\n".join(requirements) + "\n"
    
    def _generate_dockerfile(self, context: Dict[str, Any]) -> str:
        """Generate Dockerfile"""
        python_version = context.get("python_version", "3.11")
        port = context.get("port", 8000)
        workers = context.get("gunicorn_workers", 4)
        
        return f'''FROM python:{python_version}-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create non-root user
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE {port}

# Run with Gunicorn
CMD ["gunicorn", "main:app", "-w", "{workers}", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:{port}"]
'''
    
    def generate_manifests(self) -> Dict[str, str]:
        """Generate Kubernetes manifests"""
        context = self.get_context()
        manifests = {}
        
        # Namespace (for service isolation)
        manifests["namespace.yaml"] = self._generate_namespace_yaml(context)
        
        # Deployment
        manifests["deployment.yaml"] = self._generate_deployment(context)
        
        # Service
        manifests["service.yaml"] = self._generate_service(context)
        
        # ConfigMap
        manifests["configmap.yaml"] = self._generate_configmap(context)
        
        # ArgoCD Application (written separately to apps/ dir)
        self._generate_argocd_app(context)
        
        return manifests
    
    def _generate_deployment(self, context: Dict[str, Any]) -> str:
        """Generate Kubernetes Deployment"""
        name = context["name"]
        namespace = context["namespace"]
        image = context["image"]
        port = context.get("port", 8000)
        replicas = context.get("replicas", 2)
        cpu_limit = context.get("cpu_limit", "500m")
        memory_limit = context.get("memory_limit", "512Mi")
        cpu_request = context.get("cpu_request", "250m")
        memory_request = context.get("memory_request", "256Mi")
        
        env_vars = ""
        extra_env = context.get("extra_env_vars", {})
        if extra_env:
            for key, value in extra_env.items():
                env_vars += f'''
        - name: {key}
          value: "{value}"'''
        
        health_probes = ""
        if context.get("enable_health_check", True):
            health_probes = f'''
          livenessProbe:
            httpGet:
              path: /health
              port: {port}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: {port}
            initialDelaySeconds: 5
            periodSeconds: 10'''
        
        return f'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: {name}
        image: {image}
        ports:
        - containerPort: {port}
        resources:
          limits:
            cpu: {cpu_limit}
            memory: {memory_limit}
          requests:
            cpu: {cpu_request}
            memory: {memory_request}
        env:
        - name: LOG_LEVEL
          value: "{context.get("log_level", "INFO")}"{env_vars}{health_probes}
'''
    
    def _generate_service(self, context: Dict[str, Any]) -> str:
        """Generate Kubernetes Service"""
        name = context["name"]
        namespace = context["namespace"]
        port = context.get("port", 8000)
        
        return f'''apiVersion: v1
kind: Service
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  selector:
    app: {name}
  ports:
  - port: {port}
    targetPort: {port}
    protocol: TCP
'''
    
    def _generate_configmap(self, context: Dict[str, Any]) -> str:
        """Generate ConfigMap"""
        name = context["name"]
        namespace = context["namespace"]
        
        return f'''apiVersion: v1
kind: ConfigMap
metadata:
  name: {name}-config
  namespace: {namespace}
data:
  LOG_LEVEL: "{context.get("log_level", "INFO")}"
'''

